name: Laravel Build CI

on:
  push:
    branches: ["main", "Ghaza"]
  pull_request:
    branches: ["main", "Ghaza"]

jobs:
  laravel-build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: unishare
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, json, mbstring

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create storage symlink
        run: php artisan storage:link

      - name: Run Database Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: unishare
          DB_USERNAME: root
          DB_PASSWORD: null
        run: |
          php artisan migrate
          mysql -h 127.0.0.1 -u root unishare -e "INSERT INTO admin (admin_id, username, email, password, nama, profile_pic, created_at, updated_at) VALUES ('1', 'admin', 'admin@example.com', 'admin', 'Administrator', 'path/to/profile_pic.jpg', NOW(), NOW());"
      - name: Clear Config
        run: php artisan config:clear
